name: CI

on: [push]

jobs:
  checkout:

    runs-on: ubuntu-latest

    steps:
    - name: 'Check out repo'
      uses: actions/checkout@v1

    - name: 'Set up Node actions'
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: 'Install Node dependencies'
      run: npm install

  authenticate:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: 'Authenticate with Google Cloud'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

  build:
    runs-on: ubuntu-latest
    needs: authenticate

    steps:
      - name: 'Build'
        run: docker build . --tag gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}

  publish:
    runs-on: ubuntu-latest
    needs: [authenticate, build]

    steps:
      - name: 'Publish to Google Cloud'
        run: docker push gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}