name: CI

on: [push]

jobs:
  checkout:

    runs-on: ubuntu-latest

    steps:
    - name: 'Check out repo'
      uses: actions/checkout@v1

    - name: 'Set up Node actions'
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: 'Install Node dependencies'
      run: npm install

    - name: 'Build'
      run: docker build . --tag gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}

    - name: 'Authenticate'
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      continue-on-error: false
      with:
        version: '270.0.0'
        service_account_key: test #${{ secrets.GCLOUD_AUTH }}

    - name: 'Publish'
      run: docker push gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}