name: CI

on: [push]

jobs:
  checkout:

    runs-on: ubuntu-latest

    steps:
    - name: 'Check out repo'
      uses: actions/checkout@v1

  node:
    - name: 'Set up Node actions'
      needs: checkout
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: 'Install Node dependencies'
      run: npm install
      run: npm run test

  publish:
    - name: 'Authenticate with Google Cloud'
      needs: node
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
