name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Check out repo'
    - uses: actions/checkout@v1

    - name: 'Install Node dependencies'
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install

    - name: 'Authenticate with Google Cloud'
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCLOUD_AUTH }}